// <auto-generated />
namespace ProntMed.Todo.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TB_TODO : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TB_TODO));
        
        string IMigrationMetadata.Id
        {
            get { return "201602202111520_TB_TODO"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
